---
# tasks file for app
- name: Add unit file for Puma
  become: true
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  tags: app-tag
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
  tags: app-tag
