---
- name: Configure and deploy app
  hosts: app
  vars:
    db_host: 10.164.15.198
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle
      tags: deploy-tag
      notify: reload puma

  handlers:
     - name: reload puma
       become: true
       service:
         name: puma
         enabled: yes
         state: restarted