---
- name: Packer install mongodb
  hosts: all
  become: yes
  tasks:
    - name: Add an apt key for mongodb repo
      apt_key:
         keyserver: hkp://keyserver.ubuntu.com:80
         id: EA312927
         state: present
         validate_certs: no

    - name: Add mongodb repo
      apt_repository:
         repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
         state: present

    - name: Install mongodb
      package:
        name: mongodb-org
        state: present
